#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
import urllib.parse

from gh import emit, get, get_all, newest_sdks, newest_version, tag_key

UPSTREAM_REPO = "intel/compute-runtime"

# Per-series flatpak id and the packages the driver is made of. The keys are the
# names used inside the build; the values are the upstream asset name prefixes.
SERIES = {
    "main": {
        "id": "org.freedesktop.Platform.GL.OpenCLIntel",
        "description": "current driver, Gen12 and newer (Arc, Iris Xe, ...)",
        "icd_file": "intel.icd",
        "icd_library": "libigdrcl.so",
        "packages": {
            "intel-opencl-icd.ddeb": ("intel-opencl-icd-dbgsym_", 2),
            "intel-opencl-icd.deb": ("intel-opencl-icd_", 2),
            "intel-ocloc.ddeb": ("intel-ocloc-dbgsym_", 2),
            "intel-ocloc.deb": ("intel-ocloc_", 2),
            "libze-intel-gpu1.ddeb": ("libze-intel-gpu1-dbgsym_", 2),
            "libze-intel-gpu1.deb": ("libze-intel-gpu1_", 2),
        },
    },
    "legacy": {
        "id": "org.freedesktop.Platform.GL.OpenCLIntelLegacy",
        "description": "legacy driver, Gen8/Gen9/Gen11 (Broadwell .. Elkhart Lake)",
        "icd_file": "intel_legacy1.icd",
        "icd_library": "libigdrcl_legacy1.so",
        "packages": {
            "intel-opencl-icd-legacy1.ddeb": ("intel-opencl-icd-legacy1-dbgsym_", 2),
            "intel-opencl-icd-legacy1.deb": ("intel-opencl-icd-legacy1_", 2),
            "intel-level-zero-gpu-legacy1.ddeb": ("intel-level-zero-gpu-legacy1-dbgsym_", 2),
            "intel-level-zero-gpu-legacy1.deb": ("intel-level-zero-gpu-legacy1_", 2),
        },
    },
}

# intel-graphics-compiler packages are installed under /usr/local/lib, hence the
# extra directory that has to be stripped. They are shipped by a second
# repository, with a release tag referenced from the compute-runtime notes.
IGC_PACKAGES = {
    "intel-igc-core.deb": ("intel-igc-core", 3, ("devel", "media")),
    "intel-igc-opencl.deb": ("intel-igc-opencl", 3, ("devel",)),
}

GMMLIB_ASSET = "libigdgmm12_"

MANIFEST_TEMPLATE = """\
# Generated by scripts/gen-manifest.py -- do not edit.
#
# compute-runtime {version} ({series}: {description})
# intel-graphics-compiler {igc_tag}
# libigdgmm12 {gmmlib}
id: {id}
branch: '{sdk}'
runtime: org.freedesktop.Platform
runtime-version: '{sdk}'
sdk: org.freedesktop.Sdk
build-extension: true
separate-locales: false

modules:
  - name: compute-runtime
    buildsystem: simple
    build-commands:
      - install -Dm644 ${{FLATPAK_ID}}.metainfo.xml -t ${{FLATPAK_DEST}}/share/metainfo
{extract}
      - mv -- ${{FLATPAK_DEST}}/lib/x86_64-linux-gnu/* ${{FLATPAK_DEST}}/lib
      - mv -- ${{FLATPAK_DEST}}/lib/intel-opencl/* ${{FLATPAK_DEST}}/lib
      - echo {icd_library} > ${{FLATPAK_DEST}}/OpenCL/vendors/{icd_file}
      - ldconfig -n ${{FLATPAK_DEST}}/lib
    sources:
{sources}
      - type: file
        path: {metainfo}
"""

def parse_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--series", required=True, choices=sorted(SERIES))
    parser.add_argument("--version", help="upstream compute-runtime release tag "
                                          "(default: the newest release of the series)")
    parser.add_argument("--sdk", help="freedesktop SDK branch (default: the newest one)")
    parser.add_argument("--out", help="manifest path (default: build/<id>-<sdk>.yaml)")
    parser.add_argument("--report", help="write the release metadata (id, versions, ...) to this file")
    parser.add_argument("--upstream", default=UPSTREAM_REPO)
    return parser.parse_args()


def find_asset(assets, prefix, forbidden=()):
    matches = [asset for asset in assets
               if asset["name"].startswith(prefix) and asset["name"].endswith((".deb", ".ddeb"))
               and not any(word in asset["name"] for word in forbidden)]
    if len(matches) != 1:
        raise SystemExit("expected exactly one %s* package, found %s"
                         % (prefix, [asset["name"] for asset in assets]))
    return matches[0]


def igc_tag(release):
    match = re.search(r"intel-graphics-compiler/releases/tag/([^\s)\"'>]+)", release["body"] or "")
    if not match:
        raise SystemExit("no intel-graphics-compiler revision in the notes of %s" % release["tag_name"])
    return match.group(1)


def newest_gmmlib(repo):
    candidates = []
    for release in get_all("/repos/%s/releases" % repo):
        for asset in release["assets"]:
            if asset["name"].startswith(GMMLIB_ASSET):
                version = asset["name"][len(GMMLIB_ASSET):].split("_")[0]
                if tag_key(version):
                    candidates.append((tag_key(version), version, asset))
    if not candidates:
        raise SystemExit("no %s package found upstream" % GMMLIB_ASSET)
    best = max(candidates, key=lambda candidate: candidate[0])
    return best[1], best[2]


def extract_command(deb, strip):
    # Unpacking the payload to a file first keeps this independent of whether
    # upstream compressed it with gzip or zstd; tar -a picks the decompressor
    # from the file name.
    return "rm -f data.tar.* && ar x %s && tar -xaf data.tar.* --strip-components=%d -C ${FLATPAK_DEST}" % (
        os.path.basename(deb), strip)


def source_of(asset, name, strip):
    digest = asset.get("digest") or ""
    if not digest.startswith("sha256:"):
        raise SystemExit("no sha256 for %s, the release predates asset digests" % asset["name"])
    return {"type": "file", "url": urllib.parse.unquote(asset["browser_download_url"]),
            "sha256": digest[len("sha256:"):], "dest-filename": name, "strip": strip}


def main():
    args = parse_args()
    series = SERIES[args.series]
    sdk = args.sdk or newest_sdks(1)[0]

    if not args.version:
        args.version = newest_version(get_all("/repos/%s/releases" % args.upstream), args.series)
        if not args.version:
            raise SystemExit("no %s release found upstream" % args.series)

    release = get("/repos/%s/releases/tags/%s" % (args.upstream, args.version))
    if not release.get("assets"):
        raise SystemExit("release %s has no assets yet" % args.version)
    assets = release["assets"]

    sources = []
    for name, (prefix, strip) in series["packages"].items():
        sources.append(source_of(find_asset(assets, prefix), name, strip))

    gmmlib_version, gmmlib_asset = newest_gmmlib(args.upstream)
    sources.append(source_of(gmmlib_asset, "libigdgmm12.deb", 2))
    gmmlib_description = gmmlib_version

    compiler_tag = igc_tag(release)
    compiler_release = get("/repos/intel/intel-graphics-compiler/releases/tags/%s" % compiler_tag)
    for name, (prefix, strip, forbidden) in IGC_PACKAGES.items():
        asset = find_asset(compiler_release["assets"], prefix, forbidden)
        sources.append(source_of(asset, name, strip))

    out = args.out or os.path.join("build", "%s-%s.yaml" % (series["id"], sdk))
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)

    extract = []
    rendered = []
    for source in sources:
        extract.append(extract_command(source["dest-filename"], source["strip"]))
        rendered.append("      - type: file\n"
                        "        url: %s\n"
                        "        sha256: %s\n"
                        "        dest-filename: %s\n"
                        % (source["url"], source["sha256"], source["dest-filename"]))

    manifest = MANIFEST_TEMPLATE.format(
        id=series["id"], sdk=sdk, series=args.series, version=args.version,
        description=series["description"], igc_tag=compiler_tag, gmmlib=gmmlib_description,
        extract="\n".join("      - " + command for command in extract),
        sources="".join(rendered).rstrip(),
        metainfo=os.path.relpath(os.path.abspath("%s.metainfo.xml" % series["id"]),
                                 os.path.dirname(os.path.abspath(out))),
        icd_file=series["icd_file"], icd_library=series["icd_library"],
    )

    with open(out, "w") as handle:
        handle.write(manifest)
    print("wrote %s (%s %s, SDK %s)" % (out, args.series, args.version, sdk), file=sys.stderr)

    info = {"id": series["id"], "gl_name": series["id"].rsplit(".", 1)[-1], "manifest": out,
            "icd_library": series["icd_library"], "icd_file": series["icd_file"],
            "series": args.series, "description": series["description"],
            "version": args.version, "sdk": sdk,
            "igc": compiler_tag, "gmmlib": gmmlib_version}
    if args.report:
        os.makedirs(os.path.dirname(args.report) or ".", exist_ok=True)
        with open(args.report, "w") as handle:
            json.dump(info, handle, indent=2)
    emit(info)


if __name__ == "__main__":
    main()
