name: Build

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install flatpak
        run: |
          sudo apt update
          sudo apt install flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Building flatpak
        run: |
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: flatpak-bundles
          path: build/bundles/*.flatpak
